"""Write docs/results_tables.md from the committed jsons, so that every number quoted in the
write-up comes from one place. Run after `make fit` (make tables does both)."""
import glob
import json
import os
import sys
from collections import defaultdict

out = ["# Results tables\n", "Generated by `python scripts/render_tables.py` from `results/` and `runs/`. Do not edit by hand.\n"]

# ---- scaling grid
fits = json.load(open("results/fit.json")) if os.path.exists("results/fit.json") else []
if fits:
    out += ["\n## Parameter slopes of the excess over the floor (fixed-budget protocol)\n",
            "| condition | floor nT^2 | alpha, all sizes | below knee | above knee | knee m/l | broken law: below / knee / above | LOO by size: broken / additive | runs still improving |",
            "|---|---|---|---|---|---|---|---|---|"]
    for r in fits:
        b = r.get("broken_power_law", {})
        out.append(f"| beta {r['beta']}, {r['h']:.0f} m | {r['floor']:.4f} | {r.get('alpha_global', float('nan')):.2f} +- {r.get('alpha_global_err', float('nan')):.2f} "
                   f"| {r.get('alpha_small', float('nan')):.2f} +- {r.get('alpha_small_err', float('nan')):.2f} | {r.get('alpha_large', float('nan')):.2f} +- {r.get('alpha_large_err', float('nan')):.2f} "
                   f"| {r.get('knee_m_over_l', float('nan')):.1f}x | {b.get('alpha_below', float('nan')):.1f} / {b.get('knee_N', float('nan'))/1e6:.2g}M / {b.get('alpha_above', float('nan')):.1f} "
                   f"| {b.get('loo', float('nan')):.1f} / {r.get('additive_loo_sizes', float('nan')):.1f} | {r['n_unconverged']} / {r['n_runs']} |")
    out += ["\nBands are the cell-level bootstrap described in docs/problem2.md (heuristic). The broken-law parameters and the "
            "leave-one-size-out errors come from a non-convex multi-start fit and move at the 10 to 25% level between scipy "
            "versions and optimiser paths; they are quoted to one decimal for that reason. The slopes, knee ratios, floors, "
            "local deltas and floor profiles are stable.\n",
            "\n## Local data slopes, per model size (minus dlog excess / dlog D)\n"]
    for r in fits:
        out.append(f"\n**beta {r['beta']}, {r['h']:.0f} m**\n")
        segs = sorted({(g['D_from'], g['D_to']) for s in r['delta_local'].values() for g in s})
        out.append("| size | " + " | ".join(f"{a}->{b}" for a, b in segs) + " |")
        out.append("|---|" + "---|" * len(segs))
        for sz, s in r["delta_local"].items():
            d = {(g["D_from"], g["D_to"]): g for g in s}
            out.append(f"| {sz} | " + " | ".join(f"{d[k]['delta']:.2f} +- {d[k].get('err', float('nan')):.2f}" if k in d else "" for k in segs) + " |")
    out.append("\nBands: cell-level bootstrap (seeds resampled where present, singleton cells perturbed by the median seed scatter).\n")
    out += ["\n## Is the floor identified? (loss = E + A N^-alpha + B D^-delta fitted and scored in log total loss at each candidate E; the minimum is the free-floor estimate)\n",
            "| condition | exact floor | best E | best E / exact | err at best | err at exact | E range within 5% of the minimum |", "|---|---|---|---|---|---|---|"]
    for r in fits:
        for key, label in [("floor_profile", "all sizes"), ("floor_profile_large", "l, xl, xxl only")]:
            pf = r.get(key)
            if pf:
                out.append(f"| beta {r['beta']}, {r['h']:.0f} m ({label}) | {r['floor']:.3f} | {pf['best_E']:.3f} | {pf.get('best_E_over_exact', pf['best_E'] / r['floor']):.2f} | {pf['best_err']:.3f} | {pf['err_at_exact']:.3f} | [{pf['range_within_5pct'][0]:.3f}, {pf['range_within_5pct'][1]:.3f}] |")
    out.append("\nAn earlier version of this profile fitted and scored log(loss - E), whose scale changes with E; that objective favoured E near zero and was withdrawn.")
    out += ["\n## Additive form with the floor fixed to the exact value (bands: cell-level bootstrap, heuristic)\n",
            "| condition | alpha | delta | LOO over cells |", "|---|---|---|---|"]
    for r in fits:
        fx = r.get("additive_fixed_floor", {})
        dl = (f"{fx.get('delta', float('nan')):.2f} +- {fx.get('delta_err', float('nan')):.2f}") if fx.get("delta_identified", True) else "unidentified (at the optimiser bound)"
        out.append(f"| beta {r['beta']}, {r['h']:.0f} m | {fx.get('alpha', float('nan')):.2f} +- {fx.get('alpha_err', float('nan')):.2f} | {dl} | {fx.get('loo', float('nan')):.2f} |")

# ---- compute-optimal from the curves
if os.path.exists("results/compute_optimal.json"):
    co = json.load(open("results/compute_optimal.json"))
    out += ["\n## Compute-optimal allocation from the logged curves (C = 6 N S T, S = examples seen)\n",
            "| condition | alpha (fit) | delta_S (fit) | N* ~ C^ (fit) | best N along the envelope ~ C^ | runs / points |", "|---|---|---|---|---|---|"]
    for k, v in co.items():
        flag = " (form does not describe these curves: alpha above 2)" if v['alpha'] > 2 else ""
        out.append(f"| beta {v['beta']}, {v['h']:.0f} m | {v['alpha']:.2f} | {v['delta_S']:.2f} | {v['N_exponent']:.2f}{flag} | {v.get('envelope_N_exponent', float('nan')):.2f} | {v['n_runs']} / {v['n_points']} |")
    out.append("\nThe fit uses the last two thirds of each run. The envelope column is the parameter count of the best run at each compute level regressed on compute; it is the same in every condition because C depends only on size and steps and the largest model reaching a compute level is always the best, so it reflects the grid's schedule, not the task. For both: points along one cosine schedule are not independent runs of that length; the long run at step 8000 (0.876) beat the run whose schedule ended at 8000 (1.104), a 21% effect.\n")
    out += ["\n## Parameter slope at equal steps (the budget of the grid grows with size: 4k to 14k steps, lr 2e-3 to 4e-4)\n",
            "| condition | slope at 4000 steps, all sizes | slope at 8000 steps, l to xxl | grid slope (size-dependent budget) |", "|---|---|---|---|"]
    fit_by = {f"{f['beta']}_{f['h']:.0f}": f for f in fits}
    for k, v in co.items():
        g = fit_by.get(k, {})
        e4 = v.get("alpha_equal_steps_4000"); e8 = v.get("alpha_equal_steps_8000_large")
        out.append(f"| beta {v['beta']}, {v['h']:.0f} m | {e4 if e4 is not None else float('nan'):.2f} | {e8 if e8 is not None else float('nan'):.2f} | {g.get('alpha_global', float('nan')):.2f} |")
    out.append("\nRead from the logged curves at the same step for every size, so the step-count part of the size-dependent budget is removed; the learning rate still differs by size.")
    out.append("\nCaveat: points along one cosine schedule are not independent runs of that length; the long run at step 8000 (0.876) beat the run whose schedule ended at 8000 (1.104), a 21% effect.\n")

# ---- deep-linear check
if os.path.exists("results/deep_linear.json"):
    dl = json.load(open("results/deep_linear.json"))
    out += ["\n## Deep-linear time exponent, closed-form gradient flow (docs/problem3.md, part C)\n",
            "| setting | spectrum exponent c | predicted from beta | predicted from spectrum (2c-1)/c | measured two-layer slope | one-layer, whitened |", "|---|---|---|---|---|---|"]
    for b, v in dl["unmasked"].items():
        out.append(f"| unmasked, ground level, beta {b} | {v['spectrum_exponent_c']:.2f} | {v['predicted_from_beta']:.2f} | {v['predicted_from_spectrum']:.2f} | {v['two_layer_slope']:.2f} | {v['one_layer_whitened_slope']:.2f} (not a power law) |")
    for k, v in dl["masked_whitened"].items():
        b, h = k.split("_")
        out.append(f"| 75% mask, whitened, beta {b}, {h} m | {v['spectrum_exponent_c']:.2f} | {v['predicted_from_beta']:.2f} | {v['predicted_from_spectrum']:.2f} | {v['two_layer_slope']:.2f} | |")

# ---- knee isolation and single-run checks
knee = sorted(glob.glob("runs/knee_*.json"))
if knee:
    out += ["\n## Knee isolation, beta 3.5, 200 m, D = 32768, one factor changed at a time from m\n",
            "| run | width | depth | heads | steps | params | excess over floor |", "|---|---|---|---|---|---|---|"]
    ref = {}
    for f in sorted(glob.glob("runs/vit[ml]_b3.5_h200_D32768_s0.json")):
        rr = json.load(open(f)); ref[os.path.basename(f)[3]] = rr
    for k, rr in ref.items():
        c = rr["config"]
        out.append(f"| {k} (reference) | {c['width']} | {c['depth']} | {c['heads']} | {c['steps']} | {rr['params']/1e6:.2f}M | {rr['best_val']['200.0'] - rr['floor']['200.0']:.3f} |")
    for f in knee:
        rr = json.load(open(f)); c = rr["config"]
        out.append(f"| {os.path.basename(f)[5:].split('_b3.5')[0]} | {c['width']} | {c['depth']} | {c['heads']} | {c['steps']} | {rr['params']/1e6:.2f}M | {rr['best_val']['200.0'] - rr['floor']['200.0']:.3f} |")
if os.path.exists("results/width_sweep.json"):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from magscale.plots import relabel
    ws = relabel(json.load(open("results/width_sweep.json")))
    out += ["\n## Width sweep with NTK diagnostics (128 hidden-pixel outputs, sketched gradients)\n",
            "| width | parametrisation | excess over floor | centred alignment | top-eigenvector overlap | relative change | scale ratio |", "|---|---|---|---|---|---|---|"]
    for q in sorted(ws, key=lambda q: (q["par"], q["width"])):
        out.append(f"| {q['width']} | {q['par']} | {q['loss'] - q['floor']:.3f} | {q.get('centred_alignment', q['alignment']):.3f} | {q.get('top_eigenvector_overlap', float('nan')):.3f} | {q['rel_change']:.2f} | {q['scale_ratio']:.2f} |")
    out.append("\nA lazy model would have alignment 1, overlap 1, relative change 0, scale ratio 1. The wd0 row is the width-512 SP run without weight decay.")
teach = sorted(glob.glob("runs/vit*_teacher*_*k.json"))
if teach:
    out += ["\n## Wiener-teacher runs: targets are the exact conditional mean on fixed masks, so the loss has no floor\n",
            "| run | fixed masks | steps | loss = mean squared distance to the exact conditional mean [nT^2] |", "|---|---|---|---|"]
    for f in teach:
        rr = json.load(open(f)); c = rr["config"]
        out.append(f"| {os.path.basename(f)[:-5]} | {c['teacher']} | {c['steps']} | {rr['best_val']['200.0']:.4f} |")
    out.append("\nFor comparison the 5M model trained on sampled targets with one fixed mask reached 0.96 above the floor at 8k steps (fixed-mask study, D = 32768); the 38.5M model on resampled masks reached 0.045 above the floor at 24k steps.")
ood = sorted(glob.glob("results/ood_*.json"))
if ood:
    out += ["\n## Out-of-distribution evaluation (exact floor recomputed for each condition)\n",
            "| checkpoint | trained at | sigma nT | h m | loss | floor | ratio |", "|---|---|---|---|---|---|---|"]
    for f in ood:
        rr = json.load(open(f))
        for row in rr["rows"]:
            out.append(f"| {rr['run']} | h {', '.join(f'{x:.0f}' for x in rr['train_h'])}, sigma {rr['train_sigma']} | {row['sigma']} | {row['h']:.0f} | {row['loss']:.4f} | {row['floor']:.4f} | {row['loss']/row['floor']:.2f}{'' if row['in_training'] else ' (OOD)'} |")
if os.path.exists("results/emag2.json"):
    em = json.load(open("results/emag2.json"))
    out += [f"\n## EMAG2 v3 out-of-distribution test (4 km upward-continued grid, 2-arc-minute pixels resampled to square 3.7 km pixels per tile, h/dx = 1.08, 64-pixel tiles from land aeromagnetic compilations only (EMAG2 source codes 1 to 38), 75% hidden, {em['sigma']} nT noise; checkpoint {em['run']})\n",
            "| region | tiles | fitted beta median (q10, q90) | fraction in [2.5, 4] | fraction outside the prior range [1.5, 6.5] | network MSE | Gaussian, fitted beta | Gaussian, beta 3.5, detrended prior | Gaussian, beta 3.5, stationary prior | its predicted floor | interpolation MSE | Gaussian / own floor | network / Gaussian (3.5, detrended) | network / Gaussian (3.5, stationary) | network beats interpolation | network mixing-test nonlinearity |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for k, v in em["summary"].items():
        out.append(f"| {k} | {v['tiles']} | {v['beta_median']:.2f} ({v['beta_q10']:.2f}, {v['beta_q90']:.2f}) | {v['frac_beta_in_2p5_4']:.2f} | {v.get('frac_beta_clipped', float('nan')):.2f} | {v['mse_network_median']:.2f} | {v['mse_wiener_median']:.2f} | {v.get('mse_wiener_beta35_median', float('nan')):.2f} | {v.get('mse_wiener_beta35_stationary_median', float('nan')):.2f} | {v['floor_predicted_median']:.2f} | {v['mse_interp_median']:.2f} | {v['wiener_over_own_floor_median']:.2f} | {v.get('network_over_wiener_beta35_median', float('nan')):.2f} | {v.get('network_over_wiener_beta35_stationary_median', float('nan')):.2f} | {v['frac_network_beats_interp']:.2f} | {v.get('nonlinearity_median', float('nan')):.3f} |")
    out.append("\nMedians over tiles; MSE in nT^2 after rescaling each tile to the training amplitude. Gaussian / own floor is the realised error of the exact estimator for the tile's fitted beta divided by the floor it predicts for itself; on Gaussian tiles this is about 1.1 (calibration below). Fitted slopes outside [1.5, 6.5] use the prior at the boundary. The mixing-test nonlinearity is |f(0.5 y1 + 0.5 y2) - 0.5 f(y1) - 0.5 f(y2)| / |0.5 f(y1) + 0.5 f(y2)| on hidden pixels for consecutive tiles under one mask; the synthetic table gives the same quantity on Gaussian tiles.")
    import numpy as _np
    tl = em["tiles"]
    kk = _np.array([t["kurtosis"] for t in tl]); rr = _np.array([t["mse_network"] / t["mse_wiener_beta35"] for t in tl])
    out += [f"\nTile kurtosis: median {_np.median(kk):.1f}, 90th percentile {_np.quantile(kk, 0.9):.1f} (3 for a Gaussian field). Network / Gaussian (beta 3.5) by kurtosis bin:\n",
            "| kurtosis | tiles | network / Gaussian (3.5) median |", "|---|---|---|"]
    for lo, hi, lab in [(0, 3.5, "below 3.5"), (3.5, 5, "3.5 to 5"), (5, 8, "5 to 8"), (8, 1e9, "above 8")]:
        m = (kk >= lo) & (kk < hi)
        if m.any():
            out.append(f"| {lab} | {int(m.sum())} | {_np.median(rr[m]):.2f} |")
    if os.path.exists("results/emag2_synthetic.json"):
        syn = json.load(open("results/emag2_synthetic.json"))
        out += ["\nThe same pipeline on Gaussian tiles at the same equivalent altitude (network against the beta 3.5 estimator; what the ratio is when only the spectrum is unfamiliar):\n",
                "| true beta | network MSE | Gaussian, beta 3.5 | network / Gaussian | network mixing-test nonlinearity |", "|---|---|---|---|---|"]
        for b, v in syn.items():
            out.append(f"| {b} | {v['mse_network_median']:.2f} | {v['mse_wiener_beta35_median']:.2f} | {v['ratio_median']:.2f} | {v.get('nonlinearity_median', float('nan')):.3f} |")
    if os.path.exists("results/emag2_calibration.json"):
        cal = json.load(open("results/emag2_calibration.json"))
        out += ["\nCalibration on seamless Gaussian tiles at the same equivalent altitude:\n", "| true beta | fitted beta median (q10, q90) | realised / predicted floor median (q10, q90) |", "|---|---|---|"]
        for b, v in cal.items():
            out.append(f"| {b} | {v['beta_fitted_median']:.2f} ({v['beta_q10']:.2f}, {v['beta_q90']:.2f}) | {v['ratio_median']:.2f} ({v['ratio_q10']:.2f}, {v['ratio_q90']:.2f}) |")
nt = "runs/vitl_b3.5_h200_D32768_s0_noisytarget.json"
if os.path.exists(nt) and os.path.exists("runs/vitl_b3.5_h200_D32768_s0.json"):
    a = json.load(open(nt)); b = json.load(open("runs/vitl_b3.5_h200_D32768_s0.json"))
    sig2 = a["config"]["sigma"] ** 2
    out += ["\n## Noisy targets, 5M model, beta 3.5, 200 m, D = 32768\n",
            f"loss against noisy hidden values {a['best_val']['200.0']:.3f}, minus sigma^2 = {a['best_val']['200.0'] - sig2:.3f}; loss against the clean field (reference run) {b['best_val']['200.0']:.3f}; floor {b['floor']['200.0']:.3f}. Under the Gaussian model the two predictors coincide and the losses differ by sigma^2 in expectation; the measured difference is inside the seed scatter of the 5M model."]


# ---- fixed mask
fm = json.load(open("results/fit_fm.json")) if os.path.exists("results/fit_fm.json") else []
for r in fm:
    out += [f"\n## Fixed-mask study, beta {r['beta']}, {r['h']:.0f} m: excess over the floor [nT^2]\n"]
    Ds = sorted({c["D"] for c in r["cells"]})
    out.append("| size | " + " | ".join(str(d) for d in Ds) + " |")
    out.append("|---|" + "---|" * len(Ds))
    for sz in ["xs", "s", "m", "l"]:
        cs = {c["D"]: c["excess"] for c in r["cells"] if c["size"] == sz}
        if cs:
            out.append(f"| {sz} | " + " | ".join(f"{cs[d]:.3f}" if d in cs else "" for d in Ds) + " |")
    lin = r.get("linear_reference", {})
    if lin:
        out.append("| linear regression, same mask | " + " | ".join(f"{lin[str(d)]:.4f}" if str(d) in lin else "" for d in Ds) + " |")
    out.append(f"\nSlope in N across sizes at D >= 1024: {r.get('alpha_global', float('nan')):.2f} +- {r.get('alpha_global_err', float('nan')):.2f}. Local slopes in D per size are in results/fit_fm.json.\n")

# ---- probes
for f in sorted(glob.glob("results/probes_*.json")):
    r = json.load(open(f))
    out.append(f"\n## Probes: {os.path.basename(f)[7:-5]}\n")
    for k, v in r.items():
        out.append(f"- {k}: " + ", ".join(f"{kk} {vv:.4f}" if isinstance(vv, float) else f"{kk} {vv}" for kk, vv in v.items()))

# ---- navigation
if os.path.exists("results/magnav.json"):
    r = json.load(open("results/magnav.json"))
    out += ["\n## Navigation\n"]
    for beta, a in r["altitude"].items():
        out.append(f"beta {beta}: measured slope {a['slope']:.2f}, CRB slope {a['slope_crb']:.2f}, finite-map spectrum slope {a.get('slope_spec', float('nan')):.2f}, asymptotic {a['gamma']:.2f}")
    mp = r["maps"]
    out.append(f"\nTrue map: {mp['true_map'][0]:.1f} +- {mp['true_map'][1]:.1f} m (spread over maps)\n")
    out += ["| lines every | method | map rms nT | position rms m | spread over maps |", "|---|---|---|---|---|"]
    for k, v in mp["maps"].items():
        sp, name = k.split(":")
        out.append(f"| {int(sp)*100} m | {name} | {v['map_rms']:.3f} | {v['nav_rms']:.1f} | {v['nav_sd']:.1f} |")

# ---- compute used
hours = defaultdict(float)
n_runs = 0
for f in glob.glob("runs/*.json"):
    r = json.load(open(f))
    n_runs += 1
    name = os.path.basename(f)
    group = ("width" if name.startswith("width") else "unet" if name.startswith("unet") else "knee" if name.startswith("knee")
             else "fixed-mask" if name.endswith("_fm.json") else "teacher" if "_teacher" in name else "xxs" if name.startswith("vitxxs")
             else "ablations" if any(t in name for t in ["_long", "_bigdata", "_ref", "_noalt", "_lines", "_alt", "_noisytarget"]) else
             "seeds" if "_s1.json" in name or "_s2.json" in name else "small-D" if "_D256_" in name or "_D1024_" in name else "main grid")
    hours[group] += r.get("wall_time_s", 0) / 3600
out += ["\n## Compute used\n", f"{n_runs} training runs, {sum(hours.values()):.1f} GPU-hours of recorded wall time:\n"]
out += [f"- {k}: {v:.2f} h" for k, v in sorted(hours.items(), key=lambda kv: -kv[1])]
n_hw = sum(1 for f in glob.glob("runs/*.json") if json.load(open(f)).get("samples_per_s"))
out.append(f"\n{n_hw} of {n_runs} runs record the GPU, precision and throughput (the fields were added after the first runs).")
out.append("\nplus the 40 CPU linear-reference jobs (about 10 minutes each).")

os.makedirs("docs", exist_ok=True)
open("docs/results_tables.md", "w").write("\n".join(out) + "\n")
print("wrote docs/results_tables.md")
